/**
 * FormulaService
 *
 * Manages the Formula Vault and recall sessions.
 * The KEY operation is RECALL — student produces the formula from memory,
 * not just views it. Recall evidence feeds MasteryService.
 *
 * Daily recall list is generated by selecting:
 *   1. Formulas due for review (next_review_at <= now)
 *   2. Formulas never reviewed (no formula_reviews entry)
 *   3. Formulas recently failed
 * Ordered by importance DESC.
 */

import { getServiceClient } from "@tillu/database";
import { TilluError, ValidationError } from "@tillu/utilities";
import { createLogger } from "@tillu/logging";
import { z } from "zod";

const logger = createLogger({ service: "formula_service" });

// ── Input schemas ─────────────────────────────────────────────────────────────

export const RecallOutcomeSchema = z.enum(["recalled", "partial", "failed"]);

export const SubmitRecallSchema = z.object({
  formula_id:    z.string().uuid(),
  outcome:       RecallOutcomeSchema,
  student_answer: z.string().optional(),
});

export type RecallOutcome = z.infer<typeof RecallOutcomeSchema>;
export type SubmitRecallInput = z.infer<typeof SubmitRecallSchema>;

// ── Recall interval logic (simple spaced repetition for formulas) ─────────────

const RECALL_INTERVALS: Record<RecallOutcome, number> = {
  recalled: 48,   // 2 days
  partial:  12,   // 12 hours
  failed:   4,    // 4 hours
};

// ── Service ───────────────────────────────────────────────────────────────────

export class FormulaService {
  /** Get all formulas for a subject */
  async getFormulasBySubject(subjectId: string) {
    const db = getServiceClient();
    const { data, error } = await db
      .from("formulas")
      .select(`
        id, name, expression, description, variables, category, importance,
        concepts ( id, name ),
        subjects ( id, name, code )
      `)
      .eq("subject_id", subjectId)
      .order("importance", { ascending: false });

    if (error) throw new TilluError(error.message, "DATABASE_ERROR", true);
    return data ?? [];
  }

  /** Get a single formula by id */
  async getFormula(formulaId: string) {
    const db = getServiceClient();
    const { data, error } = await db
      .from("formulas")
      .select("*, concepts(id, name), subjects(id, name, code)")
      .eq("id", formulaId)
      .single();

    if (error || !data) {
      throw new TilluError("Formula not found", "NOT_FOUND", false, { formula_id: formulaId });
    }
    return data;
  }

  /**
   * Get today's recall list for a student.
   * Combines: overdue reviews + never-reviewed important formulas, limit 10.
   */
  async getDailyRecallList(studentId: string, subjectId?: string, limit = 10) {
    const db = getServiceClient();

    // Formulas that are overdue or never reviewed for this student
    // We get all formula_reviews for this student, find overdue ones
    const now = new Date().toISOString();

    // Get the latest review per formula for this student
    const { data: reviews } = await db
      .from("formula_reviews")
      .select("formula_id, outcome, next_review_at, created_at")
      .eq("student_id", studentId)
      .order("created_at", { ascending: false });

    // Map: formula_id → latest review
    const latestReview = new Map<string, { outcome: string; next_review_at: string | null }>();
    for (const r of reviews ?? []) {
      if (!latestReview.has(r.formula_id)) {
        latestReview.set(r.formula_id, { outcome: r.outcome, next_review_at: r.next_review_at });
      }
    }

    // Get all formulas (optionally filtered by subject)
    let formulaQuery = db
      .from("formulas")
      .select("id, name, expression, category, importance, subject_id, subjects(name, code)")
      .order("importance", { ascending: false });

    if (subjectId) {
      formulaQuery = formulaQuery.eq("subject_id", subjectId);
    }

    const { data: allFormulas } = await formulaQuery;

    const dueFormulas = (allFormulas ?? [])
      .filter((f) => {
        const review = latestReview.get(f.id);
        if (!review) return true; // never reviewed → due
        if (!review.next_review_at) return true;
        return review.next_review_at <= now; // overdue
      })
      .slice(0, limit);

    logger.info("formula_service.daily_list", {
      student_id: studentId,
      count: dueFormulas.length,
    });

    return dueFormulas;
  }

  /**
   * Submit a recall attempt.
   * Records the outcome and schedules the next review.
   * Returns the updated review record.
   */
  async submitRecall(studentId: string, input: SubmitRecallInput) {
    const parsed = SubmitRecallSchema.safeParse(input);
    if (!parsed.success) {
      throw new ValidationError("Invalid recall data", { errors: parsed.error.flatten() });
    }

    const { formula_id, outcome, student_answer } = parsed.data;

    // Verify formula exists
    await this.getFormula(formula_id);

    const nextReviewHours = RECALL_INTERVALS[outcome];
    const nextReviewAt = new Date(Date.now() + nextReviewHours * 3_600_000).toISOString();

    const db = getServiceClient();
    const { data, error } = await db
      .from("formula_reviews")
      .insert({
        student_id:     studentId,
        formula_id,
        outcome,
        student_answer: student_answer ?? null,
        next_review_at: nextReviewAt,
      })
      .select()
      .single();

    if (error || !data) {
      throw new TilluError(
        error?.message ?? "Failed to record recall",
        "DATABASE_ERROR",
        true
      );
    }

    logger.info("formula_service.recall_submitted", {
      student_id: studentId,
      formula_id,
      outcome,
      next_review_at: nextReviewAt,
    });

    return { ...data, next_review_at: nextReviewAt };
  }

  /** Get recall history for a formula */
  async getRecallHistory(studentId: string, formulaId: string, limit = 20) {
    const db = getServiceClient();
    const { data, error } = await db
      .from("formula_reviews")
      .select("id, outcome, student_answer, next_review_at, created_at")
      .eq("student_id", studentId)
      .eq("formula_id", formulaId)
      .order("created_at", { ascending: false })
      .limit(limit);

    if (error) throw new TilluError(error.message, "DATABASE_ERROR", true);
    return data ?? [];
  }

  /** Get recall stats: how many recalled vs partial vs failed */
  async getRecallStats(studentId: string) {
    const db = getServiceClient();

    // Get all latest reviews (one per formula)
    const { data: allReviews } = await db
      .from("formula_reviews")
      .select("formula_id, outcome, created_at")
      .eq("student_id", studentId)
      .order("created_at", { ascending: false });

    const latestPerFormula = new Map<string, string>();
    for (const r of allReviews ?? []) {
      if (!latestPerFormula.has(r.formula_id)) {
        latestPerFormula.set(r.formula_id, r.outcome);
      }
    }

    const outcomes = [...latestPerFormula.values()];
    return {
      total:    outcomes.length,
      recalled: outcomes.filter((o) => o === "recalled").length,
      partial:  outcomes.filter((o) => o === "partial").length,
      failed:   outcomes.filter((o) => o === "failed").length,
    };
  }
}
